### ISSUE TITLE
能否考虑加上中世纪那种鸟嘴型的口罩🤔比较硬核😂

### ISSUE THREAD

**Issue by ImVictorCheng** [idealclover/Wear-A-Mask#1]

**Comment by idealclover** [comment]
如果方便的话可以提供一下素材图呢

**Comment by ImVictorCheng** [comment]
https://banner2.cleanpng.com/20180805/whu/kisspng-latex-mask-plague-doctor-venice-medieval-swords-renaissance-clothing-shields-he-5b674c049ef671.7698753315334963246511.jpg

**Comment by idealclover** [comment]
素材版权存疑，且不是特别美观，暂时close吧
