### ISSUE TITLE
关于wx:for的问题

### ISSUE THREAD

**Issue by spirodelazz** [idealclover/Wear-A-Mask#5]
在imageeditor.js中声明了长度为18的数组imgList
![image](https://user-images.githubusercontent.com/45561781/80797332-277c3300-8bd4-11ea-91ad-b82583d4fc98.png)
然后在imageeditor.html中通过wx:for去获取那18张图片，最终之后显示7张
![image](https://user-images.githubusercontent.com/45561781/80797349-34008b80-8bd4-11ea-8cc0-b71e0ecbca45.png)
必须要在imgList前用点去补充
![image](https://user-images.githubusercontent.com/45561781/80797501-93f73200-8bd4-11ea-8624-8e31a78a6cfd.png)
请问下这是什么原因

**Comment by idealclover** [comment]
Have been fixed in the newest version, but I forgot the detail.

已经在最新版修了，但是忘记了细节
